language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  - composer
  - $HOME/.composer/cache

php:
  - 5.3
  - 5.6
  - 7.0

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar
    - WP_VERSION=latest

before_script:
  - bash bin/install-package-tests.sh

script: ./vendor/bin/behat
